# -*- coding: utf-8 -*-
"""Evolução e Previsão de Preços Imobiliários.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C4VR5TX9SBZYLayL1MOf-hzRkLdcQupt

# **Evolução e Previsão de Preços Imobiliários**


---


### Sprint 1 - Tratar e Explorar os Dados (EDA)
Objetivos desta sprint:


*   Entendimento da base e das variáveis
*   Limpeza e padronização dos dados (nulos, tipos, outiliers)
*   Análise exploratória para identificar padrões e correlações iniciais
*   Levantamento de hipóteses sobre os fatores que influenciem o preço dos imóveis

# 1. Imports e configurações
"""

import warnings
import kagglehub
import numpy as np
import pandas as pd
import seaborn as sns
import importlib.metadata
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.compose import make_column_selector, ColumnTransformer
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder, StandardScaler, MinMaxScaler

warnings.filterwarnings ('ignore')

# Estilo dos gráficos
sns.set_theme(style='darkgrid', palette='muted')
plt.rcParams['figure.dpi'] = 120

#Reprodutibilidade
np.random.seed (42)

print('Bibliotecas carregadas com sucesso.')
print(f'Pandas versão: {importlib.metadata.version("pandas")}')
print(f'Matplotlib versão: {importlib.metadata.version("matplotlib")}')
print(f'Numpy versão: {importlib.metadata.version("matplotlib")}')
print(f'Seaborn versão: {importlib.metadata.version("seaborn")}')

"""# 2. Carregando o Dataset"""

# Baixe o dataset em https://www.kaggle.com/datasets/omniamahmoudsaeed/real-estate-sales-2001-2022

# Baixando a última versão
path = kagglehub.dataset_download("omniamahmoudsaeed/real-estate-sales-2001-2022")

print("Caminho para o dataset:", path)

df = pd.read_csv(f'{path}/Real_Estate_Sales_2001-2022_GL.csv')
df.head()

"""# 3. Limpeza e Padronização dos Dados

Etapas:


*   Remoção de duplicados
*   Tratamento de nulos
*   Correção de tipos
*   Remoção de outliers extremos



"""

df_clean = df.copy()
print(f'Shape inicial: {df_clean.shape}')
print('===============================')

# 1. Duplicatas
n_dup = df_clean.duplicated().sum()
df_clean = df_clean.drop_duplicates()
print(f'Número de duplicatas removidas: {n_dup}')

# 2. Extraindo mês e ano da coluna de data
if 'Date Recorded' in df_clean.columns:
    df_clean['Date Recorded'] = pd.to_datetime(df_clean['Date Recorded'])
    df_clean['Month'] = df_clean['Date Recorded'].dt.month
    df_clean['Year'] = df_clean['Date Recorded'].dt.year
    print('Colunas Year e Month extraidas com sucesso.')

# 3. SaleAmount: Remover vendas com valor zero ou negativo
if 'Sale Amount' in df_clean.columns:
    n_zero = (df_clean['Sale Amount'] <= 0).sum()
    df_clean = df_clean[df_clean['Sale Amount'] >  0]
    print(f'Número de vendas com valor zero ou negativo removidas: {n_zero}')

# 4. AssedValue: Remover valor zero ou negativo
if 'Assessed Value' in df_clean.columns:
    n_zero = (df_clean['Assessed Value'] <= 0).sum()
    df_clean = df_clean[df_clean['Assessed Value'] >  0]
    print(f'Número de avaliações com valor zero ou negativo removidas: {n_zero}')

# 5. Removendo outliers em SaleAmount
if 'Sale Amount' in df_clean.columns:
  p99 = df_clean['Sale Amount'].quantile(0.99)
  n_outlier = (df_clean['Sale Amount'] > p99).sum()
  df_clean = df_clean[df_clean['Sale Amount'] <= p99]
  print(f'Número de outliers em SaleAmount removidas: {n_outlier}')

# 6. Substituindo nulos por 'Desconhecido' em Residential Type
if 'Residential Type' in df_clean.columns:
  n_nulos = df_clean['Residential Type'].isnull().sum()
  df_clean['Residential Type'] = df_clean['Residential Type'].fillna('Desconhecido')
  print(f'Número de nulos em Residential Type substituídos por "Desconhecido": {n_nulos}')

# 7. Padronizar nomes de colunas
df_clean.columns = (
    df_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
)

print(f'===============================')
print(f'Shape final: {df_clean.shape}')
print(f'Registros removidos no total: {df.shape[0] - df_clean.shape[0]}')

"""# 4. Análise Exploratória dos Dados (EDA)"""

df_clean['residential_type'] = df_clean['residential_type'].replace({'Single Family':0, 'Condo': 1, 'Two Family':2, 'Three Family': 3, 'Four Family': 4, 'Desconhecido': 5})
df_clean.head()

plt.figure(figsize=(12, 12))
# Select only numerical features for correlation calculation
numerical_df = df_clean.select_dtypes(include=['number'])  # This line is new
df_corr = numerical_df.corr() # Changed to numerical_df from df
sns.heatmap(df_corr, annot=True, cmap='coolwarm')
plt.title('Matriz de Correlação')
plt.show()

df_clean.dtypes
df_clean.head()

propriedade = df_clean["property_type"].value_counts()
propriedade

residencial = df_clean["residential_type"].value_counts()
residencial

list = df_clean["list_year"].value_counts()
list

year = df_clean["year"].value_counts()
year

sns.scatterplot(data=df_clean, x='residential_type', y='sale_amount')
plt.title('Relação entre Tipo Residencial e Valor de Venda')
plt.show()

sns.scatterplot(data=df_clean, x='sale_amount', y='property_type')
plt.title('Relação entre Tipo Residencial e Valor de Venda')
plt.show()

df_clean['residential_type'] = df_clean['residential_type'].replace({'Single Family':0, 'Condo': 1, 'Two Family':2, 'Three Family': 3, 'Four Family': 4})
df_clean.head()

sns.histplot(data=df_clean, x='sale_amount', bins=20, kde=True, color='skyblue')

plt.title('Distribuição da Variável X')
plt.xlabel('Valor')
plt.ylabel('Frequência')
plt.show()

sns.lineplot(data=df_clean, x='year', y='sale_amount', estimator='mean', errorbar=None, color='blue')
plt.title('Média do Valor de Venda por Ano')
plt.xlabel('Ano')
plt.ylabel('Média do Valor de Venda')
plt.show()

sns.scatterplot(data=df_clean, x='year', y='sale_amount', alpha=0.5)
plt.title('Relação entre Ano e Valor de Venda (Dispersão)')
plt.xlabel('Ano')
plt.ylabel('Valor de Venda')
plt.show()

sales_by_town = df_clean.groupby('town')['sale_amount'].mean().sort_values(ascending=False)

plt.figure(figsize=(12, 6))
sns.barplot(x=sales_by_town.head(10).index, y=sales_by_town.head(10).values, palette='viridis')
plt.title('Top 10 Cidades por Média de Preço de Vendas')
plt.xlabel('Cidade')
plt.ylabel('Média do Valor de Venda')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(data=df_clean, x='sales_ratio', bins=50, kde=True, color='purple')
plt.title('Distribuição da Razão de Vendas (Sales Ratio)')
plt.xlabel('Razão de Vendas')
plt.ylabel('Frequência')
plt.grid(True)
plt.show()

import matplotlib.ticker as mticker

# Filtrar para imóveis residenciais unifamiliares (Single Family)
df_single_family = df_clean[df_clean['residential_type'] == 0].copy()

yearly_sales_count = df_single_family.groupby(df_single_family['date_recorded'].dt.to_period('Y')).size()

plt.figure(figsize=(15, 8))
yearly_sales_count.plot(kind = 'line', color = 'orange', marker = 'o', markersize = 8)
ax = plt.gca()
ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, p: f'{x:,.0f}'))
plt.title('Vendas Anuais de Imóveis Residenciais Unifamiliares entre 2010 - 2022', fontsize = 16)
plt.xlabel('Ano')
plt.ylabel('Número de Vendas')
plt.grid(True, linestyle = '--', alpha = 0.6)
plt.show()

yearly_sales = df_single_family.groupby(df_single_family['date_recorded'].dt.year)['sale_amount'].sum()
yearly_sales_int = yearly_sales.astype('int64')
formatted_sales = yearly_sales.apply(lambda x: f"${x:,.0f}")
print(formatted_sales)

df_clean.describe()

#serial, data_recorded
#tratar

df_clean.isnull().sum()

"""# Sprint 2 - Preparação para modelagem
Objetivos desta sprint:


*   Carregar o dataset limpo gerado na Sprint 1
*   Converter todas as colunas categoricas em numéricas (encoding)
*   Normalizar todas as colunas numéricas

# 5. Remoção de colunas inúteis para o modelo
"""

# Colunas a descartar (não agregam valor preditivo)
COLS_TO_DROP = [
    'serial_number', 'date_recorded', 'address',
    'assessor_remarks', 'opm_remarks', 'location'
]

df_model = df_clean.drop(columns=COLS_TO_DROP)
print(f'Colunas removidas: {COLS_TO_DROP}')
print(f'Colunas restantes: {df_model.columns.tolist()}')

"""# 6. Encoding de Colunas Categóricas

O `Ordinal Encoder` converte cada valor único da coluna em um inteiro (0, 1, 2, 3)
"""

categorical_cols = df_model.select_dtypes(include=['object']).columns.tolist()
print(f'Colunas para OrdinalEconder: {categorical_cols}')

df_encoded = df_model.copy()

ord_encoder = OrdinalEncoder(
    handle_unknown='use_encoded_value',
    unknown_value=-1
)

df_encoded[categorical_cols] = ord_encoder.fit_transform(
    df_encoded[categorical_cols].astype(str)
)

print('\nEncoding aplicado. Amostra:')
display(df_encoded[categorical_cols].head())
print(f'\nColunas object restantes: {df_encoded.select_dtypes(include=["object"]).columns.tolist()}')

"""# 7. Normalização de Features Numéricas (StandardScaler)

O `Standard Scaler` transforma cada coluna para ter media 0 e desvio padrão 1:

$$
x_{scaled} = \frac{x - μ}{σ}
$$
"""

TARGET_COL = 'sale_amount'
df_encoded.head()

y = df_encoded[TARGET_COL].copy()
X = df_encoded.drop(columns=TARGET_COL)

scaler = StandardScaler()
X_scaled = pd.DataFrame(
    scaler.fit_transform(X),
    columns=X.columns,
    index=X.index
)

df_final = X_scaled.copy()
df_final[TARGET_COL] = y.values

print('Verificação após StandardScaler:')
display(X_scaled.describe().loc[['mean', 'std']].round(2))

display(df_final)

"""# 8. Dividir os dados em Treino e Teste para o modelo"""

# Separando em atributos e respostas para treino e teste

atributos_treino, atributos_teste, respostas_treino, respostas_teste = train_test_split(X, y, test_size = 0.25, random_state = 42)

modelo = {
    'Decision Tree': DecisionTreeRegressor(max_depth=10, random_state=42),
    'Random Forest': RandomForestRegressor(n_estimators=20, max_depth=10, random_state=42),
    'Linear Regression': LinearRegression(),
    'Ridge': Ridge(alpha=1.0)
}

resultados = {}

for nome_modelo, modelo in modelo.items():
    modelo.fit(atributos_treino, respostas_treino)
    predicoes = modelo.predict(atributos_teste)

    mae = mean_absolute_error(respostas_teste, predicoes)
    rmse = mean_squared_error(respostas_teste, predicoes)

    resultados[nome_modelo] = {'MAE': mae, 'RMSE': rmse}
    print(f'\n{nome_modelo}')
    print(f'MAE: {mae}')
    print(f'RMSE: {rmse}')

df_resultados = pd.DataFrame(resultados).T

df_resultados['MAE'].plot.barh(figsize=(8,4))
plt.xlabel('Erro (USD)')
plt.title('Comparação entre modelos (MAE)')
plt.tight_layout()
plt.show()

df_resultados['RMSE'].plot.barh(figsize=(8,4))
plt.xlabel('Erro (USD)')
plt.title('Comparação entre modelos (RMSE)')
plt.tight_layout()
plt.show()